export const algorithmActionTypes = {
  PROCESS_START: "PROCESS_START",
  PROCESS_FAILURE: "PROCESS_FAILURE",
  FETCH_ALGORITHMS_SUCCESS: "FETCH_ALGORITHMS_SUCCESS",
  ADD_ALGORITHM_SUCCESS: "ADD_ALGORITHM_SUCCESS",
  ADD_ALGORITHM: "ADD_ALGORITHM",
  UPDATE_ALGORITHM: "UPDATE_ALGORITHM_NAME_SUCCESS",
  DELETE_ALGORITHM: "DELETE_ALGORITHM",
};
