name: Deploy to VMs

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Frontend VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_CLIENT_PORT }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/dev/LeetCodeRecorder/client
            git pull
            npm install
            npm run build
            sudo rm -rf /var/www/ylslc/
            sudo mv build /var/www/ylslc/

    #   - name: Deploy Backend to VM2
    #     uses: appleboy/ssh-action@v1.0.0
    #     with:
    #       host: ${{ secrets.VM2_HOST }}
    #       username: ${{ secrets.VM2_USER }}
    #       key: ${{ secrets.VM2_SSH_KEY }}
    #       script: |
    #         cd /path/to/backend-repo
    #         git pull origin main
    #         ./gradlew build
    #         sudo systemctl restart springboot-app.service
