name: Deploy Frontend to S3 and Invalidate CloudFront

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Change to client directory
        run: cd client

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build React application
        run: npm run build
        working-directory: ./client

      - name: Deploy to S3
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: client/build
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: "{.*/**,**}"
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} # The CloudFront Distribution ID to invalidate
          invalidation: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
