name: Deploy Frontend to S3 and Invalidate CloudFront

on:
  push:
    branches: [main] # Or any branches you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Change to client directory
        run: cd client

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build React application
        run: npm run build
        working-directory: ./client

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete --bucket ylslc.org --source-dir 'client/build'
        env:
          AWS_S3_BUCKET: ylslc.org
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2"

      - name: Invalidate CloudFront Distribution
        uses: chetan/invalidate-cloudfront-action@v1
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} # Your CloudFront distribution ID
          PATHS: "/*"
          AWS_REGION: "ap-southeast-2" # Your AWS region (Sydney)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
