name: Deploy Spring Boot App

on:
  push:
    branches:
      - develop
    paths:
      - "server/**"
      - ".github/workflows/server-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Remote VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SERVER_VM_SSH_KEY }}
          port: 2223
          script: |
            export DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}"
            export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export UPGRADE_SECRET_KEY="${{ secrets.UPGRADE_SECRET_KEY }}"

            cd LeetCodeRecorder
            git pull
            cd ylslc
            ./mvnw clean package
            cd target
            rm ylslc-0.0.1-SNAPSHOT.jar.original || true
            cd ..
            sudo cp target/ylslc-0.0.1-SNAPSHOT.jar /opt/ylslc/ylslc-0.0.1-SNAPSHOT.jar
            sudo systemctl restart ylslc.service
