name: Deploy Spring Boot to S3

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./ylslc
          file: ./ylslc/Dockerfile
          push: true
          tags: edisonyls/ylslc-spring:latest

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key_pair.pem
          chmod 600 ~/.ssh/key_pair.pem
          ssh-keyscan -H 54.253.11.131 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/key_pair.pem ec2-user@54.253.11.131
          sudo docker pull edisonyls/ylslc-spring:latest
          sudo docker stop spring_app || true
          sudo docker rm spring_app || true
          sudo docker run -d --name spring_app -p 80:8080 edisonyls/ylslc-spring:latest
